address = "localhost:35987"
system  = true
rate    = "8M"
block   = 1200
count   = 4
buffer  = "32K"

[[route]]
address = "localhost:41001"
count = 8
rate  = "4M"
block = 1200
keep  = true

[[route]]
address = "localhost:41002"
count = 2
rate  = "16M"
block = 1200
keep  = true

[[route]]
address = "localhost:43003"
count = 4
rate  = "16M"
block = 1200
keep  = true
